version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
      MYSQL_DATABASE: user_authentication 
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      dbUser: root  
      dbPass: "1234"
      dbHost: mysql  
      dbPort: 3306  
      dbName: user_authentication 

  frontend:
    build: ./frontend/fe
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080

volumes:
  db_data:
